# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_url(c(chicago_model = "https://spectral-bullfinch.d01bf.fleeting.rstd.io/rsconnect/inspections-result-pin/"))
v <- vetiver_pin_read(b, "chicago_model")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
